version: '3.8'
services:
  build:
    container_name: soap-build
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./target:/app/target
    command: mvn clean install

  server:
    container_name: soap-server
    build:
      context: .
      dockerfile: Dockerfile
    image: soaptubes-2:latest
    command: --default-authentication-plugin=mysql_native_password
    depends_on:
      - database
    ports:
      - "3003:3003"
    env_file:
      - .env

  database:
    container_name: soap-db
    image: mysql
    restart: always
    volumes:
      - ./migration/service-soap.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./mysql-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "9902:3306"
